# Google credentials and configuration
google_client_id:      YOUR_CLIENT_ID
google_client_secret:  YOUR_CLIENT_SECRET
google_project_id:     giftthecode:us-central1:mydb

# options are "cloudsql", "mongodb", or "datastore"
bookshelf_backend: cloudsql

# configure CloudSQL backend
mysql_dsn: "mysql:host=104.154.184.147;port=3306;dbname=mydb"
mysql_user: root
mysql_password: test123
cloudsql_connection_name: "giftthecode:us-central1:mydb"

# configure Mongo backend
# mongo_url: YOUR_MONGODB_URL
# mongo_database: YOUR_MONGO_DATABASE
# mongo_collection: YOUR_MONGO_COLLECTION
